version: "3.2"

services:
  dev:
    container_name: octan-appchain
    image: paritytech/ci-linux:974ba3ac-20201006
    working_dir: /var/www/octan-appchain
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/octan-appchain/.cargo
    volumes:
      - .:/var/www/octan-appchain
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/octan-appchain --dev --ws-external"
